name: Build wheels

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
# Windows is broken
#          - windows-2019
          - macos-14

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5

      # Installing libffi to build cffi
      - if: matrix.os == 'ubuntu-24.04'
        name: Install Ubuntu prerequisites
        run: |
          sudo apt update
          sudo apt install -y libffi8
          ls /usr/local/lib/x86_64-linux-gnu/pkgconfig/usr/local/lib/pkgconfig
          ls /usr/local/share/pkgconfig
          ls /usr/lib/x86_64-linux-gnu/pkgconfig
          ls /usr/lib/pkgconfig
          ls /usr/share/pkgconfig

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.2.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # Use the `build` frontend instead of `pip` to allow in-tree
          # builds (which `pip` will eventually migrate to as well).
          CIBW_BUILD_FRONTEND: "build"
          CIBW_BEFORE_ALL_LINUX: |
            rm -rf build .eggs
          CIBW_BEFORE_ALL_MACOS: |
            rm -rf build .eggs
            brew install automake
          CIBW_SKIP: "pp*"

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
