name: Build wheels

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          # cibuildwheel installs lower version of setuptools
          # that selects incorrect MSVC and thus fails to build.
          # Migrating to pyproject.toml can set the setuptools
          # version requirement, but we don't have it yet.
          # - windows-2022
          - macOS-14

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # Use the `build` frontend instead of `pip` to allow in-tree
          # builds (which `pip` will eventually migrate to as well).
          CIBW_BUILD_FRONTEND: "build"
          CIBW_BEFORE_ALL_LINUX: |
            rm -rf build .eggs
          CIBW_BEFORE_ALL_MACOS: |
            rm -rf build .eggs
            brew install automake
          CIBW_SKIP: "pp*"

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
